---
- name: Add apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add mongodb package repository
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Convert Timezone to KST
  timezone:
    name: Asia/Seoul

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Creates chrony directory
  file:
    path: /etc/chrony
    state: directory

- name: Create ntp config file from template
  template:
    src: chrony.conf.template
    dest: /etc/chrony/chrony.conf
  notify:
    - restart chrony

- name: Create xfs filesystem on data disk blocks
  filesystem:
    fstype: xfs
    dev: /dev/{{ data_disk_device_name }}
  when: data_disk_device_name in ansible_devices

- name: Creates data volume directory
  file:
    path: "{{ mongo_data_path }}"
    state: directory

- name: Check that the data directory exists
  stat:
    path: "{{ mongo_data_path }}"
  register: data_directory

- name: Mount and bind a volume
  mount:
    path: "{{ mongo_data_path }}"
    src: /dev/{{ data_disk_device_name }}
    fstype: xfs
    state: mounted
  when: data_disk_device_name in ansible_devices

- name: Swappiness for MongoDB
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Change owner for mongodb directory
  file:
    path: "{{ mongo_data_path }}"
    owner: mongodb
    group: mongodb
  when: data_directory.stat.exists

- name: Create directory for private key
  file:
    path: "{{ private_key_path }}"
    state: directory

- name: Create Private Key for mongo access
  copy:
    src: mongo-shard.pem
    dest: "{{ private_key_path }}/{{ private_key }}"
    mode: '0400'
    owner: mongodb
    group: mongodb

- name: Install python package (pymongo)
  pip:
    name:
      - pymongo

- name: Start service mongod if not started and enabled
  service:
    name: mongod
    state: started
    enabled: yes

